### ISSUE TITLE
Can implement in mobile device?

### ISSUE THREAD

**Issue by skaka0190** [sudheeshshetty/Chat#2]
I want to implement this chat my mobile app project. Is it possible to implement in apk?

**Comment by worldsgen** [comment]
Yes , it's possible , you just need to go in localhost:8080 in your phone

**Comment by skaka0190** [comment]
@Mehdi574 thanks for the reply but I already implemented with new way😊

**Comment by MeanDevMaster** [comment]
> Yes , it's possible , you just need to go in localhost:8080 in your phone

Hello. Can you please help me with this error I am receiving when I try to start the server?

```
MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections
    at NativeConnection.Connection.openUri (C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\connection.js:693:13)
    at C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\index.js:345:10
    at C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\index.js:1135:10)
    at Mongoose.connect (C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\index.js:344:20)
    at Object.<anonymous> (C:\Users\Master\Desktop\Chat-master\model\model.js:15:10)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\Master\Desktop\Chat-master\controller\controller.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
[nodemon] app crashed - waiting for file changes before starting...
```
