### ISSUE TITLE
MongooseError: Can't call `openUri()` on an active connection with different connection strings.

### ISSUE THREAD

**Issue by MeanDevMaster** [sudheeshshetty/Chat#4]
I get this error when trying to start the server.

MongooseError: Can't call `openUri()` on an active connection with different connection strings. Make sure you aren't calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections
    at NativeConnection.Connection.openUri (C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\connection.js:693:13)
    at C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\index.js:345:10
    at C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\helpers\promiseOrCallback.js:30:10)
    at Mongoose._promiseOrCallback (C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\index.js:1135:10)
    at Mongoose.connect (C:\Users\Master\Desktop\Chat-master\node_modules\mongoose\lib\index.js:344:20)
    at Object.<anonymous> (C:\Users\Master\Desktop\Chat-master\model\model.js:15:10)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\Master\Desktop\Chat-master\controller\controller.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by coderkrys737** [comment]
Try commenting out line 19 in the model/model.js file which says,
`mongoose.connect('mongodb://localhost/mongodb')`

Since line 5 already established a connection, I am not sure why the duplicate is needed.

This worked for me.
