### ISSUE TITLE
Unhandled "error" event

### ISSUE THREAD

**Issue by ThinBucket82549** [sudheeshshetty/Chat#6]
There is a weird error when someone signs up 
![20220730_195508](https://user-images.githubusercontent.com/73562905/181905211-80736940-d288-4984-adee-96603fe29c9a.jpg)

**Comment by ThinBucket82549** [comment]
Then it just crashes... help?

**Comment by coderkrys737** [comment]
The mongoose version in package.json needs to be updated. 

This is the root error
`Error [MongoError]: Unsupported OP_QUERY command: insert. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
    at Function.MongoError.create (D:\Repositories\Chat\node_modules\mongodb-core\lib\error.js:31:11)
    at D:\Repositories\Chat\node_modules\mongodb-core\lib\connection\pool.js:497:72
    at authenticateStragglers (D:\Repositories\Chat\node_modules\mongodb-core\lib\connection\pool.js:443:16)
    at Connection.messageHandler (D:\Repositories\Chat\node_modules\mongodb-core\lib\connection\pool.js:477:5)
    at Socket.<anonymous> (D:\Repositories\Chat\node_modules\mongodb-core\lib\connection\connection.js:333:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  ok: 0,
  code: 352,
  codeName: 'UnsupportedOpQueryCommand'
}`

Please see this documentation for more details.
[https://www.mongodb.com/docs/v6.0/release-notes/6.0-compatibility/#legacy-opcodes-removed](url)
